events {}
http {
  upstream user_service       { server user-service:3001; }
  upstream product_service    { server product-service:3002; }
  upstream cart_service       { server cart-service:3003; }
  upstream order_service      { server order-service:3004; }
  upstream payment_service    { server payment-service:3005; }
  upstream notification_service { server notification-service:3006; }

  server {
    listen 80;

    location /api/users/      { proxy_pass http://user_service/; }
    location /api/products/   { proxy_pass http://product_service/; }
    location /api/cart/       { proxy_pass http://cart_service/; }
    location /api/orders/     { proxy_pass http://order_service/; }
    location /api/payments/   { proxy_pass http://payment_service/; }
    location /api/notify/     { proxy_pass http://notification_service/; }
  }
}